### PR TITLE
CI(containers): fix dev image for local development case

### LINKED ISSUE #6494: devcontainer does not build proprely for devel
### Issue Summary

the "postStartCommand" portion of the .devcontainer.json fail.

the entrypoint.sh script still points to requirements-dev.txt which does not exist anymore

### Which components of AVD are impacted

others

### AVD version

devel

### Ansible version

_No response_

### Python version

_No response_

### How do you run AVD ?

AVD container

### Steps to reproduce

```shell
fork avd devel and build a container
```

### Relevant log output

```shell

```

### Contributing Guide

- [x] I agree to follow this project Code of Conduct

### PR DESCRIPTION
**Pull request by ankudinov**
## Change Summary

This PR fixes dev AVD container image to support local development use case.
`requirements-dev.txt` will be now replaced with editable install from the container workspace

## Related Issue(s)

Fixes #6494 

## How to test

Fork and clone AVD. Open the repository in dev container using VSCode.

### CODE REVIEW

**Review by ClausHolbechArista — APPROVED** [review]

File: containers/dev/.devcontainer/entrypoint.sh [hunk 1]
```diff
@@ -14,9 +14,9 @@ if [ -z "$(command -v ansible)" ]; then
     pip install "pyavd[ansible] @ ${PYAVD_INSTALL_LOCATION}"
     ansible-galaxy collection install --force ${AVD_INSTALL_PATH}
   # otherwise install requirements and collection from container workspace
-  elif [ -f ${CONTAINER_WORKSPACE}/python-avd/pyproject.toml ] && [ -f ${CONTAINER_WSF_AVD_PATH}/requirements-dev.txt ] ; then
-    # Install pyavd from source and dev requirements from file
-    pip install ${CONTAINER_WORKSPACE}/python-avd[ansible-collection] -r ${CONTAINER_WSF_AVD_PATH}/requirements-dev.txt
+  elif [ -f ${CONTAINER_WORKSPACE}/python-avd/pyavd/__init__.py ]; then
+    # Install pyavd from source
+    pip install --editable "${CONTAINER_WORKSPACE}/python-avd[ansible]"
```
Comment (gmuloc) [inline containers/dev/.devcontainer/entrypoint.sh]: so here you would be losing all the dev requirements (molecule and the rest) is it on purpose?

I was thinking you would have to add `--group dev` to the command (and make sure pip is >=25.1)

Comment (ankudinov) [reply containers/dev/.devcontainer/entrypoint.sh]: great find! resolved

**Review by gmuloc — APPROVED** [review]
